name: Secret Scanner

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build scanner
        run: go build -o secret-scanner

      - name: Run scanner with annotations
        run: ./secret-scanner scan . --config rules/rules.yaml --github
